import {
  AttendanceStatus,
  PrismaClient,
  ProviderType,
  RegistrationStatus,
  SessionFormat,
  SessionStatus,
  UserRole,
} from "@prisma/client";

const prisma = new PrismaClient();

const agencies = [
  { id: "agency-child-care-circuit", name: "Child Care Circuit", region: "Northeast" },
  { id: "agency-seven-hills", name: "Seven Hills Family Services", region: "Central" },
  { id: "agency-eec-boston", name: "EEC Boston Office", region: "Boston" },
  { id: "agency-pace-cc", name: "Pace CC", region: "Southeast" },
  { id: "agency-valley-opp", name: "Valley Opportunity Council", region: "Western" },
  { id: "agency-child-care-choices", name: "Child Care Choices", region: "Metro Boston" },
  { id: "seed-agency-boston", name: "Boston Child Care Resource Center", region: "Boston" },
  { id: "seed-agency-northeast", name: "Northeast Family Support Agency", region: "Northeast" },
  { id: "seed-agency-western", name: "Western MA Early Learning Network", region: "Western Massachusetts" },
];

const sessions = [
  {
    id: "session-eec-orientation-2026-06-14",
    agencyId: "agency-child-care-circuit",
    title: "EEC Mandatory Orientation",
    region: "Northeast",
    format: SessionFormat.VIRTUAL,
    startsAt: new Date("2026-06-14T14:00:00.000Z"),
    endsAt: new Date("2026-06-14T16:30:00.000Z"),
    capacity: 25,
    meetingUrl: "https://example.com/zoom-link",
  },
  {
    id: "session-licensing-review-2026-06-21",
    agencyId: "agency-seven-hills",
    title: "Licensing Regulation Review",
    region: "Central",
    format: SessionFormat.IN_PERSON,
    startsAt: new Date("2026-06-21T17:00:00.000Z"),
    endsAt: new Date("2026-06-21T19:30:00.000Z"),
    capacity: 25,
    locationName: "Seven Hills Family Services",
    address: "Worcester, MA",
  },
  {
    id: "session-health-safety-2026-06-28",
    agencyId: "agency-eec-boston",
    title: "Health and Safety Essentials",
    region: "Boston",
    format: SessionFormat.VIRTUAL,
    startsAt: new Date("2026-06-28T13:00:00.000Z"),
    endsAt: new Date("2026-06-28T15:30:00.000Z"),
    capacity: 25,
    meetingUrl: "https://example.com/teams-link",
  },
  {
    id: "seed-session-boston-virtual",
    agencyId: "seed-agency-boston",
    title: "Family Child Care Orientation",
    description: "Introductory orientation for new family child care providers.",
    region: "Boston",
    format: SessionFormat.VIRTUAL,
    startsAt: new Date("2026-06-09T14:00:00.000Z"),
    endsAt: new Date("2026-06-09T16:00:00.000Z"),
    capacity: 30,
    meetingUrl: "https://example.com/zoom/boston-orientation",
  },
  {
    id: "seed-session-boston-person",
    agencyId: "seed-agency-boston",
    title: "Group Child Care Licensing Basics",
    description: "In-person session covering licensing steps and required documents.",
    region: "Boston",
    format: SessionFormat.IN_PERSON,
    startsAt: new Date("2026-06-16T13:00:00.000Z"),
    endsAt: new Date("2026-06-16T16:00:00.000Z"),
    capacity: 25,
    locationName: "100 Cambridge Street, Boston, MA",
  },
  {
    id: "seed-session-northeast-virtual",
    agencyId: "seed-agency-northeast",
    title: "Provider Orientation: Northeast Region",
    description: "Virtual orientation for providers in the Northeast region.",
    region: "Northeast",
    format: SessionFormat.VIRTUAL,
    startsAt: new Date("2026-06-23T17:00:00.000Z"),
    endsAt: new Date("2026-06-23T19:00:00.000Z"),
    capacity: 40,
    meetingUrl: "https://example.com/zoom/northeast-orientation",
  },
  {
    id: "seed-session-western-past",
    agencyId: "seed-agency-western",
    title: "Western MA Provider Orientation",
    description: "Completed test session with attendance data.",
    region: "Western Massachusetts",
    format: SessionFormat.IN_PERSON,
    startsAt: new Date("2026-05-23T14:00:00.000Z"),
    endsAt: new Date("2026-05-23T16:00:00.000Z"),
    capacity: 20,
    locationName: "Springfield Public Library, Springfield, MA",
  },
];

const providerPrograms = [
  {
    id: "program-little-learners",
    stateProviderId: "PID-100112",
    programName: "Little Learners Child Care Center",
    providerType: ProviderType.CENTER_BASED,
    address: "18 Beacon St, Boston, MA 02108",
    city: "Boston",
    region: "Boston",
    licensingRegion: "Metro Boston",
    subsidyRegion: "Metro Boston",
  },
  {
    id: "program-bright-futures",
    stateProviderId: "PID-100214",
    programName: "Bright Futures Family Child Care",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    address: "42 Main St, Worcester, MA 01608",
    city: "Worcester",
    region: "Central",
    licensingRegion: "Central",
    subsidyRegion: "Central",
  },
  {
    id: "program-rising-stars",
    stateProviderId: "PID-100318",
    programName: "Rising Stars Early Learning",
    providerType: ProviderType.CENTER_BASED,
    address: "240 River St, Springfield, MA 01103",
    city: "Springfield",
    region: "Western",
    licensingRegion: "Western",
    subsidyRegion: "Western",
  },
  {
    id: "program-harbor-view",
    stateProviderId: "PID-100427",
    programName: "Harbor View Kids Academy",
    providerType: ProviderType.CENTER_BASED,
    address: "88 Harbor St, New Bedford, MA 02740",
    city: "New Bedford",
    region: "Southeast",
    licensingRegion: "Southeast",
    subsidyRegion: "Southeast",
  },
  {
    id: "program-northeast-neighborhood",
    stateProviderId: "PID-100533",
    programName: "Northeast Neighborhood Child Care",
    providerType: ProviderType.CENTER_BASED,
    address: "12 Essex St, Lawrence, MA 01840",
    city: "Lawrence",
    region: "Northeast",
    licensingRegion: "Northeast",
    subsidyRegion: "Northeast",
  },
  {
    id: "program-tiny-explorers",
    stateProviderId: "PID-100641",
    programName: "Tiny Explorers Family Child Care",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    address: "17 Maple Ave, Cambridge, MA 02139",
    city: "Cambridge",
    region: "Metro Boston",
    licensingRegion: "Metro Boston",
    subsidyRegion: "Metro Boston",
  },
  {
    id: "program-boston-school-age",
    stateProviderId: "PID-100755",
    programName: "Boston Community School-Age Program",
    providerType: ProviderType.SCHOOL_AGE,
    address: "145 Tremont St, Boston, MA 02111",
    city: "Boston",
    region: "Boston",
    licensingRegion: "Metro Boston",
    subsidyRegion: "Metro Boston",
  },
  {
    id: "program-pioneer-valley",
    stateProviderId: "PID-100862",
    programName: "Pioneer Valley Learning Hub",
    providerType: ProviderType.CENTER_BASED,
    address: "9 Market St, Northampton, MA 01060",
    city: "Northampton",
    region: "Western",
    licensingRegion: "Western",
    subsidyRegion: "Western",
  },
];

const staffUsers = [
  {
    id: "staff-child-care-circuit",
    email: "ccrr.circuit@example.com",
    name: "Sarah Mitchell",
    role: UserRole.CCRR_STAFF,
    agencyId: "agency-child-care-circuit",
    clerkUserId: process.env.SEED_CCRR_CLERK_USER_ID ?? null,
  },
  {
    id: "staff-seven-hills",
    email: "ccrr.sevenhills@example.com",
    name: "David Okonkwo",
    role: UserRole.CCRR_STAFF,
    agencyId: "agency-seven-hills",
    clerkUserId: process.env.SEED_CCRR_SEVEN_HILLS_CLERK_USER_ID ?? null,
  },
  {
    id: "staff-eec-boston",
    email: "ccrr.boston@example.com",
    name: "Lisa Park",
    role: UserRole.CCRR_STAFF,
    agencyId: "agency-eec-boston",
    clerkUserId: process.env.SEED_CCRR_BOSTON_CLERK_USER_ID ?? null,
  },
  {
    id: "staff-eec-admin",
    email: "eec.admin@example.com",
    name: "EEC State Admin",
    role: UserRole.EEC_ADMIN,
    agencyId: null,
    clerkUserId: process.env.SEED_EEC_CLERK_USER_ID ?? null,
  },
  {
    id: "seed-staff-boston",
    email: "staff.boston@example.com",
    name: "Boston CCR&R Staff",
    role: UserRole.CCRR_STAFF,
    agencyId: "seed-agency-boston",
    clerkUserId: process.env.SEED_BOSTON_RESOURCE_CLERK_USER_ID ?? null,
  },
  {
    id: "seed-staff-northeast",
    email: "staff.northeast@example.com",
    name: "Northeast CCR&R Staff",
    role: UserRole.CCRR_STAFF,
    agencyId: "seed-agency-northeast",
    clerkUserId: process.env.SEED_NORTHEAST_RESOURCE_CLERK_USER_ID ?? null,
  },
  {
    id: "seed-staff-omar",
    email: "omar.admin@example.com",
    name: "Omar EEC Admin",
    role: UserRole.EEC_ADMIN,
    agencyId: null,
    clerkUserId: process.env.SEED_OMAR_EEC_CLERK_USER_ID ?? null,
  },
];

const providerUsers = [
  {
    id: "appuser-maria-rodriguez",
    clerkUserId: "seed-provider-maria-rodriguez",
    email: "m.rodriguez@example.com",
    firstName: "Maria",
    lastName: "Rodriguez",
    providerName: "Maria Rodriguez",
    organizationName: "Little Learners Child Care Center",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100112",
    phone: "(555) 010-0001",
  },
  {
    id: "appuser-james-chen",
    clerkUserId: "seed-provider-james-chen",
    email: "j.chen@daycare.org",
    firstName: "James",
    lastName: "Chen",
    providerName: "James Chen",
    organizationName: "Bright Futures Family Child Care",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    stateProviderId: "PID-100214",
    phone: "(555) 010-0002",
  },
  {
    id: "appuser-althea-jenkins",
    clerkUserId: "seed-provider-althea-jenkins",
    email: "ajenkins@provider.net",
    firstName: "Althea",
    lastName: "Jenkins",
    providerName: "Althea Jenkins",
    organizationName: "Northeast Neighborhood Child Care",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100533",
    phone: "(555) 010-0003",
  },
  {
    id: "appuser-devon-walsh",
    clerkUserId: "seed-provider-devon-walsh",
    email: "d.walsh@brightstart.org",
    firstName: "Devon",
    lastName: "Walsh",
    providerName: "Devon Walsh",
    organizationName: "Rising Stars Early Learning",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100318",
    phone: "(555) 010-0004",
  },
  {
    id: "appuser-priya-nair",
    clerkUserId: "seed-provider-priya-nair",
    email: "priya.nair@example.com",
    firstName: "Priya",
    lastName: "Nair",
    providerName: "Priya Nair",
    organizationName: "Harbor View Kids Academy",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100427",
    phone: "(555) 010-0005",
  },
  {
    id: "appuser-tomas-herrera",
    clerkUserId: "seed-provider-tomas-herrera",
    email: "t.herrera@littlesteps.org",
    firstName: "Tomás",
    lastName: "Herrera",
    providerName: "Tomás Herrera",
    organizationName: "Tiny Explorers Family Child Care",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    stateProviderId: "PID-100641",
    phone: "(555) 010-0006",
  },
  {
    id: "appuser-elena-vasquez",
    clerkUserId: "seed-provider-elena-vasquez",
    email: "e.vasquez@cambridgekids.org",
    firstName: "Elena",
    lastName: "Vasquez",
    providerName: "Elena Vasquez",
    organizationName: "Cambridge Kids Academy",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100901",
    phone: "(555) 010-0007",
  },
  {
    id: "appuser-robert-kim",
    clerkUserId: "seed-provider-robert-kim",
    email: "r.kim@brightbeginnings.org",
    firstName: "Robert",
    lastName: "Kim",
    providerName: "Robert Kim",
    organizationName: "Bright Beginnings Child Care",
    providerType: ProviderType.CENTER_BASED,
    stateProviderId: "PID-100902",
    phone: "(555) 010-0008",
  },
  {
    id: "appuser-sophia-martinez",
    clerkUserId: "seed-provider-sophia-martinez",
    email: "s.martinez@littlestars.org",
    firstName: "Sophia",
    lastName: "Martinez",
    providerName: "Sophia Martinez",
    organizationName: "Little Stars Learning Center",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    stateProviderId: "PID-100903",
    phone: "(555) 010-0009",
  },
];

const registrations = [
  {
    id: "registration-maria-eec-june-14",
    sessionId: "session-eec-orientation-2026-06-14",
    userId: "appuser-maria-rodriguez",
    providerName: "Maria Rodriguez",
    organizationName: "Little Learners Child Care Center",
    contactEmail: "m.rodriguez@example.com",
    phone: "(555) 010-0001",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-02T15:00:00.000Z"),
  },
  {
    id: "registration-james-eec-june-14",
    sessionId: "session-eec-orientation-2026-06-14",
    userId: "appuser-james-chen",
    providerName: "James Chen",
    organizationName: "Bright Futures Family Child Care",
    contactEmail: "j.chen@daycare.org",
    phone: "(555) 010-0002",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    status: RegistrationStatus.ATTENDED,
    attendanceStatus: AttendanceStatus.ATTENDED,
    notes: "Arrived 5 mins late",
    checkedInAt: new Date("2026-06-14T14:05:00.000Z"),
    completedAt: new Date("2026-06-14T16:30:00.000Z"),
    createdAt: new Date("2026-06-04T12:00:00.000Z"),
  },
  {
    id: "registration-althea-eec-june-14",
    sessionId: "session-eec-orientation-2026-06-14",
    userId: "appuser-althea-jenkins",
    providerName: "Althea Jenkins",
    organizationName: "Northeast Neighborhood Child Care",
    contactEmail: "ajenkins@provider.net",
    phone: "(555) 010-0003",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-05T18:00:00.000Z"),
  },
  {
    id: "registration-devon-licensing-june-21",
    sessionId: "session-licensing-review-2026-06-21",
    userId: "appuser-devon-walsh",
    providerName: "Devon Walsh",
    organizationName: "Rising Stars Early Learning",
    contactEmail: "d.walsh@brightstart.org",
    phone: "(555) 010-0004",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-09T14:00:00.000Z"),
  },
  {
    id: "registration-priya-licensing-june-21",
    sessionId: "session-licensing-review-2026-06-21",
    userId: "appuser-priya-nair",
    providerName: "Priya Nair",
    organizationName: "Harbor View Kids Academy",
    contactEmail: "priya.nair@example.com",
    phone: "(555) 010-0005",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-11T16:30:00.000Z"),
  },
  {
    id: "registration-tomas-health-june-28",
    sessionId: "session-health-safety-2026-06-28",
    userId: "appuser-tomas-herrera",
    providerName: "Tomás Herrera",
    organizationName: "Tiny Explorers Family Child Care",
    contactEmail: "t.herrera@littlesteps.org",
    phone: "(555) 010-0006",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-18T13:00:00.000Z"),
  },
  {
    id: "registration-elena-boston-licensing-june-16",
    sessionId: "seed-session-boston-person",
    userId: "appuser-elena-vasquez",
    providerName: "Elena Vasquez",
    organizationName: "Cambridge Kids Academy",
    contactEmail: "e.vasquez@cambridgekids.org",
    phone: "(555) 010-0007",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-03T10:00:00.000Z"),
  },
  {
    id: "registration-robert-boston-licensing-june-16",
    sessionId: "seed-session-boston-person",
    userId: "appuser-robert-kim",
    providerName: "Robert Kim",
    organizationName: "Bright Beginnings Child Care",
    contactEmail: "r.kim@brightbeginnings.org",
    phone: "(555) 010-0008",
    providerType: ProviderType.CENTER_BASED,
    status: RegistrationStatus.ATTENDED,
    attendanceStatus: AttendanceStatus.ATTENDED,
    notes: "Brought all required licensing documents",
    checkedInAt: new Date("2026-06-16T12:55:00.000Z"),
    completedAt: new Date("2026-06-16T16:00:00.000Z"),
    createdAt: new Date("2026-06-06T14:30:00.000Z"),
  },
  {
    id: "registration-sophia-boston-licensing-june-16",
    sessionId: "seed-session-boston-person",
    userId: "appuser-sophia-martinez",
    providerName: "Sophia Martinez",
    organizationName: "Little Stars Learning Center",
    contactEmail: "s.martinez@littlestars.org",
    phone: "(555) 010-0009",
    providerType: ProviderType.FAMILY_CHILD_CARE,
    status: RegistrationStatus.REGISTERED,
    attendanceStatus: AttendanceStatus.NOT_MARKED,
    notes: null,
    createdAt: new Date("2026-06-10T09:15:00.000Z"),
  },
];

async function main() {
  for (const agency of agencies) {
    await prisma.agency.upsert({
      where: { id: agency.id },
      update: agency,
      create: agency,
    });
  }

  for (const session of sessions) {
    await prisma.orientationSession.upsert({
      where: { id: session.id },
      update: {
        ...session,
        status: SessionStatus.PUBLISHED,
      },
      create: {
        ...session,
        status: SessionStatus.PUBLISHED,
      },
    });
  }

  for (const program of providerPrograms) {
    await prisma.providerProgram.upsert({
      where: { stateProviderId: program.stateProviderId },
      update: program,
      create: program,
    });
  }

  for (const staffUser of staffUsers) {
    await prisma.staffUser.upsert({
      where: { id: staffUser.id },
      update: {
        email: staffUser.email,
        name: staffUser.name,
        role: staffUser.role,
        agencyId: staffUser.agencyId,
        ...(staffUser.clerkUserId ? { clerkUserId: staffUser.clerkUserId } : {}),
      },
      create: staffUser,
    });
  }

  for (const providerUser of providerUsers) {
    await prisma.appUser.upsert({
      where: { id: providerUser.id },
      update: providerUser,
      create: {
        ...providerUser,
        role: UserRole.PROVIDER,
      },
    });
  }

  for (const registration of registrations) {
    await prisma.registration.upsert({
      where: { id: registration.id },
      update: registration,
      create: registration,
    });
  }

  if (!process.env.SEED_BOSTON_RESOURCE_CLERK_USER_ID) {
    console.log(
      "\nTip: set SEED_BOSTON_RESOURCE_CLERK_USER_ID in .env to your Clerk user ID, then re-run npm run db:seed to access /ccrr as Boston Child Care Resource Center staff.",
    );
  }
}

main()
  .then(async () => {
    await prisma.$disconnect();
  })
  .catch(async (error) => {
    console.error(error);
    await prisma.$disconnect();
    process.exit(1);
  });
